model:
  arch: medlvlm
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  language_model: "meta-llama/Llama-2-7b-chat-hf"
  ckpt: "/path/to/pretrained_checkpoint"
  use_grad_checkpoint: True
  chat_template: True
  low_resource: True
  lora_r: 64
  lora_alpha: 16
  bits: 8

datasets:
  vindrcxr_train:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  vindrcxr_val:
    eval_file_path: "/home/nngocson/FPT/grounded_diseases_test_2.json"
    img_path: "/home/nngocson/FPT/images/test"  
    max_new_tokens: 512
    batch_size: 4

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /path/to/save/folder_path